# ===========
# Final image
# ===========
FROM apache/superset

ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_EMAIL $ADMIN_EMAIL
ENV ADMIN_PASSWORD $ADMIN_PASSWORD

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py