SECRET_KEY = "MDfYkbbZVnyvB51a2X/YkiKWEZrJ5V7wpG0xmIkCF43vP9pCZ2GddbI7"
PREVENT_UNSAFE_DB_CONNECTIONS = False
PUBLIC_ROLE_LIKE_GAMMA = True
FEATURE_FLAGS = {
    "EMBEDDED_SUPERSET": True
}
SQLALCHEMY_DATABASE_URI = 'postgresql://superset:superset@db:5432/superset'
